<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
<!--        <PublishAot>true</PublishAot>-->
        <PublishTrimmed>true</PublishTrimmed>
        <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
<!--        <TrimMode>link</TrimMode>-->
        <ApplicationIcon>Assets\configuration.ico</ApplicationIcon>

        <!-- 平台特定的编译符号 -->
        <DefineConstants Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(DefineConstants);WINDOWS</DefineConstants>
        <DefineConstants Condition="$([MSBuild]::IsOSPlatform('Linux'))">$(DefineConstants);LINUX</DefineConstants>
    </PropertyGroup>
    
    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>
    
    
    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.2" />
        <PackageReference Include="Avalonia.Controls.ColorPicker" Version="12.0.2" />
        <PackageReference Include="Avalonia.Desktop" Version="12.0.2" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="H.InputSimulator" Version="1.5.0" />
        <PackageReference Include="Irihi.Ursa" Version="2.0.0" />
        <PackageReference Include="Irihi.Ursa.Themes.Semi" Version="2.0.0" />
        <PackageReference Include="CSharpFunctionalExtensions" Version="3.7.0" />
        <PackageReference Include="Semi.Avalonia" Version="12.0.1" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="Xaml.Behaviors.Interactions" Version="12.0.0" />
        <PackageReference Include="Jab" Version="0.12.0" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SpaceKat.Shared\SpaceKat.Shared.csproj" />
      <ProjectReference Include="..\Win32Helpers\Win32Helpers.csproj" />
      <ProjectReference Include="..\LinuxHelpers\LinuxHelpers.csproj" />
      <ProjectReference Include="..\PlatformAbstractions\PlatformAbstractions.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <DirectPInvoke Include="libHarfBuzzSharp" Condition="'$(PublishAot)' == 'true' And $(RuntimeIdentifier.StartsWith('win'))" />
        <NativeLibrary Include="E:\codeDir\CSharp\Avalonia\AotLibs\libHarfBuzzSharp.lib" Condition="'$(PublishAot)' == 'true' And $(RuntimeIdentifier.StartsWith('win'))" />
        <DirectPInvoke Include="libSkiaSharp" Condition="'$(PublishAot)' == 'true' And $(RuntimeIdentifier.StartsWith('win'))" />
        <NativeLibrary Include="E:\codeDir\CSharp\Avalonia\AotLibs\libSkiaSharp.lib" Condition="'$(PublishAot)' == 'true' And $(RuntimeIdentifier.StartsWith('win'))" />
        <DirectPInvoke Include="av_libglesv2" Condition="'$(PublishAot)' == 'true' And $(RuntimeIdentifier.StartsWith('win'))" />
        <NativeLibrary Include="E:\codeDir\CSharp\Avalonia\AotLibs\av_libglesv2.lib" Condition="'$(PublishAot)' == 'true' And $(RuntimeIdentifier.StartsWith('win'))" />
    </ItemGroup>
    
    </Project>
