using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace SpaceKatHIDWrapper.SourceGen;

[Generator]
public sealed class TomlEmbedGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var tomlFiles = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith(".toml", StringComparison.OrdinalIgnoreCase))
            .Select((file, ct) =>
            {
                var name = Path.GetFileNameWithoutExtension(file.Path);
                var content = file.GetText(ct)?.ToString() ?? string.Empty;
                return new TomlFile(name, content);
            })
            .Collect();

        context.RegisterSourceOutput(tomlFiles, GenerateSource);
    }

    private static void GenerateSource(SourceProductionContext spc, ImmutableArray<TomlFile> files)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("namespace SpaceKatHIDWrapper.DeviceHIDSpecs;");
        sb.AppendLine();
        sb.AppendLine("internal static class EmbeddedTomlDefaults");
        sb.AppendLine("{");

        if (files.IsEmpty)
        {
            sb.AppendLine("    // No .toml AdditionalFiles found.");
        }
        else
        {
            foreach (var file in files)
            {
                var fieldName = GetFieldName(file.Name);
                var literal = SymbolDisplay.FormatLiteral(file.Content, true);
                sb.AppendLine($"    public const string {fieldName} = {literal};");
            }
        }

        sb.AppendLine("}");

        spc.AddSource("EmbeddedTomlDefaults.g.cs",
            Microsoft.CodeAnalysis.Text.SourceText.From(sb.ToString(), System.Text.Encoding.UTF8));
    }

    private static string GetFieldName(string fileName)
    {
        return fileName switch
        {
            "devices" => "Devices",
            "devices_3dconnexion" => "Devices3DConnexion",
            _ => SnakeToPascalCase(fileName)
        };
    }

    private static string SnakeToPascalCase(string name)
    {
        var parts = name.Split('_');
        return string.Concat(parts.Select(p =>
            p.Length > 0 ? char.ToUpperInvariant(p[0]) + p.Substring(1).ToLowerInvariant() : ""));
    }

    private sealed class TomlFile
    {
        public string Name { get; }
        public string Content { get; }

        public TomlFile(string name, string content)
        {
            Name = name;
            Content = content;
        }
    }
}
