<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnableEnumGeneratorInterceptor>true</EnableEnumGeneratorInterceptor>
        <PublishTrimmed>true</PublishTrimmed>
        <LangVersion>latestmajor</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
      <PackageReference Include="HidApi.Net" Version="1.2.0" />
      <PackageReference Include="WCharT.Net" Version="0.1.3" />
      <PackageReference Include="CSharpFunctionalExtensions" Version="3.7.0" />
      <PackageReference Include="NetEscapades.EnumGenerators" Version="1.0.0-beta21" />
      <PackageReference Include="Tomlyn" Version="2.3.2" />
    </ItemGroup>
    
    <ItemGroup>
      <None Remove="hidapi.dll" />
      <Content Include="hidapi.dll" Condition="'$(PublishAot)' != 'true' And $(RuntimeIdentifier.StartsWith('win'))">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="DeviceHIDSpecs\devices.toml" />
      <AdditionalFiles Include="DeviceHIDSpecs\devices_3dconnexion.toml" />
    </ItemGroup>

    <Target Name="BuildSourceGen" BeforeTargets="BeforeBuild">
        <MSBuild Projects="..\SpaceKatHIDWrapper.SourceGen\SpaceKatHIDWrapper.SourceGen.csproj"
                 Targets="Build"
                 Properties="Configuration=$(Configuration)"
                 RemoveProperties="PublishTrimmed;PublishAot;SelfContained;RuntimeIdentifier" />
    </Target>

    <Target Name="AddSourceGenAnalyzer" BeforeTargets="CoreCompile">
        <ItemGroup>
            <Analyzer Include="..\SpaceKatHIDWrapper.SourceGen\bin\$(Configuration)\netstandard2.0\SpaceKatHIDWrapper.SourceGen.dll" />
        </ItemGroup>
    </Target>

</Project>
